/**
 * Differential test: every template rendered by worker/template.mjs must match
 * what real Jinja2 produces from the same context.
 *
 * The expected output in test/jinja-expected.json was generated by Jinja 3.1.6
 * with Flask's autoescape settings (scripts in the repo history; regenerate
 * with test/regenerate-expected.py). Comparing against the reference
 * implementation is the only way to be confident the subset renderer is right,
 * rather than merely self-consistent.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { readdirSync } from 'node:fs';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { render } from '../worker/template.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const fixture = JSON.parse(readFileSync(resolve(here, 'fixture.json'), 'utf8'));
const expected = JSON.parse(readFileSync(resolve(here, 'jinja-expected.json'), 'utf8'));

const templates = readdirSync(resolve(root, 'templates')).filter((f) => f.endsWith('.html'));

test('every template is covered by the expected output', () => {
  assert.deepEqual(templates.sort(), Object.keys(expected).sort());
});

for (const name of templates) {
  test(`${name} matches Jinja2 byte for byte`, () => {
    const source = readFileSync(resolve(root, 'templates', name), 'utf8');
    const context = { ...fixture._default, ...(fixture._overrides?.[name] ?? {}) };
    assert.equal(render(source, context), expected[name]);
  });
}
